### ISSUE TITLE
Copy themes from git repos

### ISSUE THREAD

**Issue by pascalandy** [jwasham/docker-ghost-template#2]
Hi John,

I really enjoy your setup at this point :) One big thing I would like is the ability to load a theme(s) from a git repo(s).

The goal is the avoid to manually upload themes in their running containers. That would allow us to quickly tried themes as well as developing theme just by typing `docker-compose up -d`

For example, how would you proceed to copy https://github.com/roryg/ghostwriter into /usr/src/ghost/themes/ ?

So far this is what I got:

1) I [added these 2 lines](https://gist.github.com/pascalandy/0f9c6d8f84e1701585e41e4d3c960fe6#file-entrypoint-sh-L35) to the entrypoint.sh

2) I created a [copy-themes.sh](https://gist.github.com/pascalandy/faa58fba5fc9c9530e71ea0d57f0ddad) into our directory copy

This brings the question of having ghost selecting the default theme... but this is for another moment :-p

Cheers!
Pascal

P.S. The docker team change something relate to theme but I do not understand the code here ;-/
https://github.com/docker-library/ghost/commit/8c0d010d4f6c0aa91b16ad1b9dcc09ee2a287549

**Comment by jwasham** [comment]
Hi Pascal, 
Thanks for waiting. I got around to setting a memory limit and looking into the theme question for you.

I've updated the ReadMe with info on how to add your own theme:
https://github.com/jwasham/docker-ghost-template

Once you add your theme with this method, you should be able to make changes to your new theme without restarting the container, because the directory on the host is mounted.

More in the ReadMe.

Nice theme!

By the way, the 2 lines you added to your entrypoint.sh won't work. They are written in Dockerfile syntax, but entrypoint is a bash script.
The addition by the ghost team above won't affect you.

**Comment by pascalandy** [comment]
This is pretty cool! I'll try this soon :)
